version: "3.9"  # optional since v1.27.0
services:
  frontend:
    restart: "always"
    depends_on:
    - backend
    build: ./frontend
    ports:
      - "8000:3000"
  backend:
    restart: "always"
    build: ./backend
    depends_on:
    - db
    ports:
      - "8080:3000"
    environment:
      DATABASE_NAME: "test"
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "test"
      DATABASE_HOST: "db"
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

#  postgresql:
#    image: docker.io/bitnami/postgresql:latest
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#      - POSTGRESQL_USERNAME=bn_keycloak
#      - POSTGRESQL_DATABASE=bitnami_keycloak
#    volumes:
#      - 'postgresql_data:/bitnami/postgresql'
#  keycloak:
#    restart: "always"
#    image: jboss/keycloak
#    ports:
#      - "7080:8080"
#    environment:
#      - KEYCLOAK_USER=root
#      - KEYCLOAK_PASSWORD=test
#      - KEYCLOAK_CREATE_ADMIN_USER=false
#      - DB_ADDR=postgresql
#      - DB_PORT=5432
#      - DB_USER=bn_keycloak
#      - DB_PASSWORD=""
#    depends_on:
#      - postgresql
#    volumes:
#      - './mynewtheme:/opt/bitnami/keycloak/themes/mynewtheme'
volumes:
  postgresql_data:
    driver: local
